default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: ey_test_app_development

test:
  <<: *default
  database: ey_test_app_test

production:
  <<: *default
  database: ey_test_app_production
  username: deploy
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "") %>
